### PR TITLE
Remove caret center/scale

### LINKED ISSUE #38: Remove caret dependency
caret is being used only 3 places to center and scale a matrix

https://github.com/som-shahlab/survmetabench/blob/master/survlearners/R/slasso_surv.R#L52
https://github.com/som-shahlab/survmetabench/blob/master/survlearners/R/rlasgrf.R#L75
https://github.com/som-shahlab/survmetabench/blob/master/survlearners/R/rlasso.R#L67

this seems like something that can easily be done with Base R and [caret](https://github.com/som-shahlab/survmetabench/blob/master/survlearners/DESCRIPTION#L25) can be deleted

### PR DESCRIPTION
**Pull request by erikcs**
closes #38

### CODE REVIEW

**Comment by CrystalXuR** [comment]
@erikcs The changes you have made look fine to me, but there are other places used the parameters from this standardization https://github.com/som-shahlab/survmetabench/blob/master/r-package/survlearners/R/rlasso.R#L199 Should I approve it and I can go make the rest changes

**Comment by erikcs** [comment]
Ok, thanks!

**Comment by erikcs** [comment]
You can also git checkout this branch, and push changes to it yourself!

**Comment by erikcs** [comment]
Two people can commit things on the same PR

**Comment by CrystalXuR** [comment]
right, got it, doing it now

**Review by CrystalXuR — APPROVED** [review]

**Pull request merged**
