### PR TITLE
removing Y.grid for all estimators

### PR DESCRIPTION
**Pull request by CrystalXuR**
No longer specify Y.grid and use default all unique follow-up times instead

### CODE REVIEW

**Comment by CrystalXuR** [comment]
@erikcs one check has failed and here is the message "ERROR: dependency ‘RcppEigen’ is not available for package ‘grf’", which did not happen before. Would you please take a look at the issue?

**Comment by erikcs** [comment]
Sure, that's just an annoying CRAN thing, evidently a new rcppeigen package was just released today and the install method  can't find it... 

But that is not the reason your PR fails, you missed a comma here:
Screen Shot 2022-04-08 at 08 34 20

https://github.com/som-shahlab/survmetabench/runs/5880737714?check_suite_focus=true

**Comment by CrystalXuR** [comment]
I see that now, thanks. I tried to push a fix to this branch, but it shows me this
Screen Shot 2022-04-08 at 9 02 19 AM

I did 'git pull origin master' but did not fix the problem

**Comment by erikcs** [comment]
You clicked "Merge branch 'master' into rm_Ygrid" on the website which means you need to do git pull first to update your local branch

**Comment by CrystalXuR** [comment]
Do you mean "git pull rm_Ygrid"?

**Comment by erikcs** [comment]
yes

**Pull request merged**
