### PR TITLE
Addoutput

### PR DESCRIPTION
**Pull request by CrystalXuR**
Adding a file for summarizing simulation results.

### CODE REVIEW

**Comment by CrystalXuR** [comment]
@erikcs A question for you. I did switch to this addoutput branch when I create this PR, why the log shows the other tasks that I did in other branches here

**Comment by CrystalXuR** [comment]
Never mind, I now know where did I do wrong... based on your comments in the rlearner_modify branch

**Comment by erikcs** [comment]
sounds good, "git log" is useful to keep a lookout of what your local branch history looks like

**Review by erikcs — APPROVED** [review]

**Comment by erikcs** [comment]
you have some autogenerated files to commit here though (.Rd if you run Document)

**Comment by CrystalXuR** [comment]
Removed utils.R, removed stringr package dependency, simplified R-learners, and added the simulation_output.R file

**Comment by erikcs** [comment]
Remember to click "Delete branch"

**Pull request closed without merging**
