### PR TITLE
change dontrun to donttest

### PR DESCRIPTION
**Pull request by CrystalXuR**
Test all the examples are runnable

### CODE REVIEW

**Comment by CrystalXuR** [comment]
@erikcs A question on the failing message. Here is the error it showed me
Screen Shot 2022-04-09 at 12 37 45 PM

However, under the same local branch, I have the following 
Screen Shot 2022-04-09 at 12 38 04 PM

Wonder why they don't matc?

**Comment by erikcs** [comment]
Yeah the signature in that function is not well defined with arguments and default arguments mixed , you have function(a,b,c,d=43,e=42,f)

**Comment by erikcs** [comment]
Yeah the signature in that function is not well defined with arguments and default arguments mixed , you have function(a,b,c,d=43,e=42,f)

**Comment by erikcs** [comment]
There are no files changed now in this PR

**Review by erikcs — APPROVED** [review]

**Pull request merged**
